### DISCUSSION TITLE
Spain data file is missing Spain country boundary

### DISCUSSION THREAD

**Discussion by ZogopZ** [mediagis/nominatim-docker#294] [Q&A] [answered]
**Describe the bug**
I am running a docker container for nominatim and trying to reverse geocode locations in Europe. 
This is my `docker-compose.yml` file:
```
version: "3"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.0
        restart: always
        ports:
            - "8080:8080"
        environment:
            PBF_URL: https://download.geofabrik.de/europe-latest.osm.pbf
            IMPORT_STYLE: admin
        volumes:
            - ./nominatim-data:/var/lib/postgresql/12/main
```

I can reverse geocode correctly most places but for some reason I cannot do it for Spain when using **zoom levels 0-4**.
Zoom levels 0-4 work for other countries.

I tried using Spain only `.pbf` files and my `docker-compose.yml` file looks like this:
```
version: "3"

services:
    nominatim:
        container_name: nominatim-spain
        image: mediagis/nominatim:4.0
        restart: always
        ports:
            - "8081:8081"
        environment:
            PBF_URL: http://download.geofabrik.de/europe/spain-latest.osm.pbf
            IMPORT_STYLE: admin
        volumes:
            - ./nominatim-data:/var/lib/postgresql/12/main
```
The problem persists and I cannot geocode **zoom levels 0-5**.
Other zoom levels work correctly.

**To Reproduce**
Use `docker-compose up` for either of the above files. Preferably the one with the Spain files since it's a lot smaller.

**Expected behavior**
Expected to get the reverse geocode response instead of unable to geocode.

**Screenshots & Logs**
![εικόνα](https://user-images.githubusercontent.com/55022842/153248128-082f4e42-d939-46ce-9b12-d6e8b7303732.png)

**Desktop / Server (please complete the following information):**
 - OS & Version: Debian 11
 - Docker Version: Docker version 20.10.7, build 20.10.7
 - Nominatim Version: 4.0
