### DISCUSSION TITLE
Stuck on postgresql start

### DISCUSSION THREAD

**Discussion by muhammadrivaldy** [mediagis/nominatim-docker#303] [Q&A]
I already running nominatim on docker before, and so far running well.
But two week or one month ago, I can't running nominatim on docker with docker-compose.
I use Macbook Air M1 with Rosetta.

[https://drive.google.com/file/d/14YrSncdJVr-7vE6t8L7Zr_3tQD7ul-3f/view?usp=sharing](url)

And this is my docker-compose
```
version: "3.9"

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:3.7
    restart: always
    depends_on:
      - postgres
    ports:
      - 5053:8080
    environment:
      PBF_URL: http://geo-service:8080/nominatim/osm/depok.osm.pbf
      # REPLICATION_URL: https://google.com/
      # PBF_PATH: ./osm/depok.osm.pbf
      # IMPORT_WIKIPEDIA: "false"
      # NOMINATIM_PASSWORD: "%32Tys3*uS601nU"
      # NOMINATIM_PASSWORD: postgres
    command: ["/app/init.sh"]
    volumes:
      # - ./osm/data:/nominatim/data
      - nominatim-data:/var/lib/postgresql/12/main
```

**Comment by philipkozeny** [comment]
Your drive link doesn't work. What is the error you see? May be related to: https://github.com/mediagis/nominatim-docker/issues/285

**Reply by muhammadrivaldy** [reply]
Please copy and paste the url in the new tab

**Reply by mtmail** [reply]
![8A276691-F848-4F1F-AD8E-7F7FE171CA0C](https://user-images.githubusercontent.com/3727288/155962461-bd1f5e94-a6cc-46fe-9104-4e4f262b837d.png)

**Reply by philipkozeny** [reply]
Thanks

**Comment by philipkozeny** [comment]
Try to post your docker-compose again please, seems to be incorrect, you're missing "services:" on top, etc. Please also try to use the `add code` function in the editor for the correct formatting.

**Reply by muhammadrivaldy** [reply]
```
version: "3.9"
services:
  geo-service:
    container_name: geo-service
    image: umkm/geo:latest
    restart: always
    ports:
      - 8081:8080
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "8080"
      PATH_CONF: ./config
      FILE_CONF: local.conf
      BASE_URL_CORE: "http://backend-umkm:8080"
      BASE_URL_NOMINATIM: "http://nominatim:8080"

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:3.7
    restart: always
    depends_on:
      - postgres
    ports:
      - 5053:8080
    environment:
      PBF_URL: http://geo-service:8080/nominatim/osm/depok.osm.pbf
      # REPLICATION_URL: https://google.com/
      # PBF_PATH: ./osm/depok.osm.pbf
      # IMPORT_WIKIPEDIA: "false"
      # NOMINATIM_PASSWORD: "%32Tys3*uS601nU"
      # NOMINATIM_PASSWORD: postgres
    command: ["/app/init.sh"]
    volumes:
      # - ./osm/data:/nominatim/data
      - nominatim-data:/var/lib/postgresql/12/main

  # osrm:
  #   container_name: osrm
  #   image: osrm/osrm-backend
  #   restart: always
  #   ports:
  #     - 5052:5000
  #   volumes:
  #     - ./osm/depok.osm.pbf:/data/depok.osm.pbf
  #   command: sh -c "osrm-extract -p /opt/car.lua /data/depok.osm.pbf &&
  #     osrm-partition /data/depok.osrm &&
  #     osrm-customize /data/depok.osrm &&
  #     osrm-routed --algorithm mld /data/depok.osrm"
    
  postgres:
    container_name: db-postgre
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - nominatim-data:/var/lib/postgresql/12/main

networks:
  default:
    external:
      name: networks-umkm

volumes:
  nominatim-data:
```
