### DISCUSSION TITLE
Using PBF_PATH with docker-compose

### DISCUSSION THREAD

**Discussion by aspeddro** [mediagis/nominatim-docker#324] [Q&A]
How do I configure it to use `PBF_PATH` and read the local file? Any tutorials?

The file `rj.osm` was extracted using https://extract.bbbike.org/

```yaml
version: "3"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.0
        restart: always
        ports:
            - "8080:8080"
        environment:
            # see https://github.com/mediagis/nominatim-docker/tree/master/4.0#configuration for more options
            # PBF_URL: https://download.geofabrik.de/south-america/brazil/sudeste-latest.osm.pbf
            PBF_PATH: rj.osm
            THREADS: 8
            FREEZE: true
            # REPLICATION_URL: https://download.geofabrik.de/europe/monaco-updates/
            # NOMINATIM_PASSWORD: very_secure_password
        volumes:
            - nominatim-data:/var/lib/postgresql/12/main
        shm_size: 1gb

volumes:
    nominatim-data:
```

```sh
sudo docker-compose up
```

```
[+] Running 1/0
 ⠿ Container nominatim  Created                                                                                                                                     0.0s
Attaching to nominatim
nominatim  | + trap stopServices TERM
nominatim  | + /app/config.sh
nominatim  | + id nominatim
nominatim  | user nominatim already exists
nominatim  | + echo 'user nominatim already exists'
nominatim  | + IMPORT_FINISHED=/var/lib/postgresql/12/main/import-finished
nominatim  | + TOKENIZER_DIR=/nominatim/tokenizer
nominatim  | + '[' '!' -f /var/lib/postgresql/12/main/import-finished ']'
nominatim  | + /app/init.sh
nominatim  | + OSMFILE=/nominatim/data.osm.pbf
nominatim  | + '[' '' = true ']'
nominatim  | + '[' -f '' ']'
nominatim  | + echo 'Skipping optional Wikipedia importance import'
nominatim  | Skipping optional Wikipedia importance import
nominatim  | Skipping optional GB postcode import
nominatim  | + '[' '' = true ']'
nominatim  | + '[' -f '' ']'
nominatim  | + echo 'Skipping optional GB postcode import'
nominatim  | + '[' '' = true ']'
nominatim  | + '[' -f '' ']'
nominatim  | + echo 'Skipping optional US postcode import'
nominatim  | Skipping optional US postcode import
nominatim  | + '[' '' = true ']'
nominatim  | + '[' -f '' ']'
nominatim  | + echo 'Skipping optional Tiger addresses import'
nominatim  | + '[' '' '!=' '' ']'
nominatim  | Skipping optional Tiger addresses import
nominatim  | + '[' rj.osm '!=' '' ']'
nominatim  | Reading OSM extract from rj.osm
nominatim  | + echo Reading OSM extract from rj.osm
nominatim  | + OSMFILE=rj.osm
nominatim  | + '[' '!' -f /var/lib/postgresql/12/main/PG_VERSION ']'
nominatim  | + sudo service postgresql start
nominatim  |  * Starting PostgreSQL 12 database server
nominatim  |    ...done.
nominatim  | + sudo -E -u postgres psql postgres -tAc 'SELECT 1 FROM pg_roles WHERE rolname='\''nominatim'\'''
nominatim  | + grep -q 1
nominatim  | + sudo -E -u postgres psql postgres -tAc 'SELECT 1 FROM pg_roles WHERE rolname='\''www-data'\'''
nominatim  | + grep -q 1
nominatim  | + sudo -E -u postgres psql postgres -tAc 'ALTER USER nominatim WITH ENCRYPTED PASSWORD '\''qaIACxO6wMR3'\'''
nominatim  | ALTER ROLE
nominatim  | + sudo -E -u postgres psql postgres -tAc 'ALTER USER "www-data" WITH ENCRYPTED PASSWORD '\''qaIACxO6wMR3'\'''
nominatim  | ALTER ROLE
nominatim  | + sudo -E -u postgres psql postgres -c 'DROP DATABASE IF EXISTS nominatim'
nominatim  | NOTICE:  database "nominatim" does not exist, skipping
nominatim  | DROP DATABASE
nominatim  | + chown -R nominatim:nominatim /nominatim
nominatim  | + cd /nominatim
nominatim  | + sudo -E -u nominatim nominatim import --osm-file rj.osm --threads 8
nominatim  | 2022-04-29 20:31:17: Using project directory: /nominatim
nominatim  | 2022-04-29 20:31:17: OSM file 'rj.osm' does not exist.
nominatim  | 2022-04-29 20:31:17: FATAL: Cannot access file.
nominatim exited with code 1
```
