### ISSUE TITLE
Use with docker-compose results in fixable error

### ISSUE THREAD

**Issue by jackHedaya** [mediagis/nominatim-docker#249]
**Describe the bug**
When running with docker-compose, a command needs to be specified or the following error appears:

```
ERROR: for community-network-api_nominatim_1  Cannot create container for service nominatim: No command specified
```

To fix a command that does nothing must be added.

`command: tail -f /dev/null`

**To Reproduce**
1. Create `docker-compose` without `command`
2. Attempt `docker-compose up`

**Expected behavior**
Nominatim to run with possibly a success message

**Screenshots & Logs**

This is my `docker-compose.yml`
```
services:
  nominatim:
    image: mediagis/nominatim
    ports:
      - "5100:80"
    environment:
      - PBF_URL=https://download.geofabrik.de/europe/monaco-latest.osm.pbf
      - REPLICATION_URL=https://download.geofabrik.de/europe/monaco-updates/
      - IMPORT_STYLE=address
    shm_size: 1gb
    volumes:
      - nominatim-data:/var/lib/postgresql/12/main
    command: >
      bash -c "echo 'Nominatim initialized'
      && tail -f /dev/null"

volumes:
  nominatim-data:
```
**Desktop / Server**
 - OS & Version: macOS
 - Docker Version: 3.5.2
 - Nominatim Version: 3
