### ISSUE TITLE
Docker-Compose: File "base/49153/PG_VERSION" is missing.

### ISSUE THREAD

**Issue by TurtIeSocks** [mediagis/nominatim-docker#269]
**Describe the bug**

```
nominatim    |   * optional external GB postcode table file (/nominatim/gb_postcode_data.sql.gz) not found. Skipping.
nominatim    |
nominatim    | 2021-11-18 20:49:21 == Setup finished.
nominatim    | 2021-11-18 20:49:21: Indexing places
nominatim    |
nominatim    |
nominatim    | Traceback (most recent call last):
nominatim    |   File "/usr/local/bin/nominatim", line 11, in <module>
nominatim    |     exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
nominatim    |   File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 288, in nominatim
nominatim    |     return parser.run(**kwargs)
nominatim    |   File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 92, in run
nominatim    |     return args.command.run(args)
nominatim    |   File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 129, in run
nominatim    |     indexer.index_full(analyse=not args.index_noanalyse)
nominatim    |   File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 161, in index_full
nominatim    |     conn = psycopg2.connect(self.dsn)
nominatim    |   File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 126, in connect
nominatim    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
nominatim    | psycopg2.OperationalError: FATAL:  "base/49153" is not a valid data directory
nominatim    | DETAIL:  File "base/49153/PG_VERSION" is missing.
```
**To Reproduce**
1. `docker-compose up -d && docker-compose logs -f`
2. Imports the osm file, eventually crashes with the error

```
docker-compose.yml
version: "3"

services:
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:3.7
    restart: always
    ports:
      - "8080:8080"
    environment:
      PBF_PATH: /nominatim/data/merged.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/europe/monaco-updates/
      IMPORT_US_POSTCODES: 'true'
    volumes:
      - nominatim-data:/var/lib/postgresql/12/main
      - /home/test/nominatim:/nominatim/data
    shm_size: 1gb
volumes:
  nominatim-data: null
```
**Expected behavior**
I expected it to not crash, while I haven't used this specific .pbf file before, I've had success with using regular docker containers in the past. I'm using a custom merged .pbf and not very concerned about updates, just left the REPLICATION_URL in since it crashes without it.
