### ISSUE TITLE
[4.0] UK/US postcodes not imported on fresh install

### ISSUE THREAD

**Issue by iAlex97** [mediagis/nominatim-docker#299]
**Describe the bug**
I will focus on UK as there are about 1.7 mil postcodes in the `CodePoint OpenData set` and the problem is easily observable.

**To Reproduce**
1. Set up a new nominatim installation with the following docker-compose file:

```yaml
version: "2.1"

services:
    nominatim-api:
        environment:
            - PBF_URL=https://download.geofabrik.de/europe/great-britain-latest.osm.pbf
            - REPLICATION_URL=https://download.geofabrik.de/europe/great-britain-updates/
            - IMPORT_WIKIPEDIA=true
            - IMPORT_US_POSTCODES=false
            - IMPORT_GB_POSTCODES=true
            - NOMINATIM_PASSWORD=pass
            - IMPORT_STYLE=address
            - THREADS=10
            - PGCTLTIMEOUT=300
        shm_size: '64g'
        image: mediagis/nominatim:4.0
        ports:
            - "25000:8080"
        volumes:
            - nominatim-data-gb:/var/lib/postgresql/12/main
volumes:
    nominatim-data-gb:
        external: true
        name: nominatim-data-gb
```

2. Choose some postcodes from the imported dataset:
```
B68 0NP,52.46604,-1.98571
...
M32 0QT,53.46157,-2.32451
...
SL9 7QE,51.58680,-0.55451
```

3. Query nominatim installation about those postcodes:
```bash
curl http://localhost:25000/search?postalcode=M32+0QT
[]

curl http://localhost:25000/search?postalcode=B68+0NP
[]

curl http://localhost:25000/search?postalcode=SL9+7QE
[]
```

**Expected behavior**
Nominatim should return some information, just like the public deployment:
```bash
curl https://nominatim.openstreetmap.org/search.php?postalcode=SL9+7QE&format=jsonv2
[{"place_id":287976321,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","boundingbox":["51.4268","51.7468","-0.71451","-0.39451"],"lat":"51.5868","lon":"-0.55451","display_name":"Gerrards Cross, Buckinghamshire, South East England, England, SL9 7QE, United Kingdom","place_rank":25,"category":"place","type":"postcode","importance":0.325}]
``` 

**Screenshots & Logs**

Upon further investigation, I found out that the postcodes did not exist in the `location_postcode` table:
```
nominatim=# select * from location_postcode where postcode='M32 0QT';
 place_id | parent_place_id | rank_search | rank_address | indexed_status | indexed_date | country_code | postcode | geometry
----------+-----------------+-------------+--------------+----------------+--------------+--------------+----------+----------
(0 rows)
```

Counting the `gb` postcodes yielded about 375k results, way less than the 1.7 mil in the imported dataset.

```
nominatim=# select country_code, count(*) from location_postcode group by country_code;
 country_code |  count
--------------+---------
 fr           |       1
 gb           |  374955
(2 rows)
```

I then downloaded the gb csv from nominatim and ran the update command:

```bash
wget https://www.nominatim.org/data/gb_postcodes.csv.gz

nominatim refresh --postcodes
```

After those operations were completed, the postcodes were successfully indexed into the db:

```
nominatim=# select * from location_postcode where postcode='M32 0QT';
 place_id | parent_place_id | rank_search | rank_address | indexed_status |       indexed_date        | country_code | postcode |                      geometry
----------+-----------------+-------------+--------------+----------------+---------------------------+--------------+----------+----------------------------------------------------
  6474294 |         5346266 |          25 |            5 |              0 | 2022-02-23 17:16:11.85217 | gb           | M32 0QT  | 0101000020E6100000B8CCE9B2989802C04968CBB914BB4A40
(1 row)

nominatim=# select country_code, count(*) from location_postcode group by country_code;
 country_code |  count
--------------+---------
 fr           |       1
 gb           | 1727335
(2 rows)
```

Now the nominatim api successfully returns a non empty array:

```bash
curl http://localhost:25000/search?postalcode=SL9+7QE
[{"place_id":6871861,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","boundingbox":["51.4268","51.7468","-0.71451","-0.39451"],"lat":"51.5868","lon":"-0.55451","display_name":"Gerrards Cross, Buckinghamshire, South East England, England, SL9 7QE, United Kingdom","place_rank":25,"category":"place","type":"postcode","importance":0.325}]
```

**Desktop / Server (please complete the following information):**
 - OS & Version: `Ubuntu 20.04.2 LTS`
 - Docker Version: `20.10.9, build c2ea9bc`
 - Nominatim Version: `4.0.1`

**Additional context**
Quoting from the [4.0.0 release notes](https://github.com/osm-search/Nominatim/releases/tag/v4.0.0):

> The format of some external data sources (postcodes, TIGER data) has changed to CSV. You need to download new versions of them.

Let me know if I should submit a PR as well as the fix probably implies some 5 min changes.

Cheers!
