### ISSUE TITLE
Init script stops on symlink to zip codes

### ISSUE THREAD

**Issue by stAn47** [mediagis/nominatim-docker#340]
Hello, i mounted project dir from host to docker container and upon docker restart i am getting an error: 

+ '[' /nominatim/extras/gb_postcodes.csv.gz = true ']'
+ '[' -f /nominatim/extras/gb_postcodes.csv.gz ']'
+ ln -s /nominatim/extras/gb_postcodes.csv.gz /nominatim/gb_postcodes.csv.gz
ln: failed to create symbolic link '/nominatim/gb_postcodes.csv.gz': File exists

my file layout is: 
```
            PBF_PATH: /nominatim/data/planet.pbf
            REPLICATION_URL: http://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/replication/minute/
            NOMINATIM_FLATNODE_FILE: /nominatim/flatnode.file
            IMPORT_GB_POSTCODES: /nominatim/extras/gb_postcodes.csv.gz
            IMPORT_TIGER_ADDRESSES: /nominatim/extras/wikimedia-importance.sql.gz
            IMPORT_US_POSTCODES: /nominatim/extras/us_postcodes.csv.gz

volumes:
            - nominatim-data:/var/lib/postgresql/12/main
            - /opt/nominatim/project:/nominatim
```

i am trying to import whole planet, but haven't yet been sucessfull (on hetzner ax101 128gb ram and 4tb nvmes), it would be enough for me to use just the zip codes, countries and cities of whole planet, but i haven't yet found proper data sources for this. 

once i remove the symlinks from the directory, it continues initialization - for now i see that it might take up to 2 days for the DB to initliaze on this 5ghz 16 core server... 

i think the solution to my problem above is to adjust the init scripts to check if the symlink already exists so it doesn't fail on creating a new one:
ln -s /nominatim/extras/gb_postcodes.csv.gz /nominatim/gb_postcodes.csv.gz

i haven't yet finished full inititialization, so maybe that's why it always starts again and again. 

best regards, stan
