### ISSUE TITLE
Is ICU Tokenizer working correctly?

### ISSUE THREAD

**Issue by hasanli-orkhan** [mediagis/nominatim-docker#353]
Is ICU Tokenizer working correctly?

**Describe the bug**
Below I have added the configuration with which I launch the container.
It seems to me that the tokenizer is not working
For example:
When making request: 
`localhost:8080/search?q=bak` or  `localhost:8080/search?q=ba` finds nothing
But when I provide the fullname `localhost:8080/search?q=bak` then the results appear

**To Reproduce**
```yaml
version: '3.8'

services:
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      # see https://github.com/mediagis/nominatim-docker/tree/master/4.0#configuration for more options
      PBF_URL: https://download.geofabrik.de/asia/azerbaijan-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/asia/azerbaijan-updates/
      NOMINATIM_PASSWORD: nominatim
      NOMINATIM_TOKENIZER: icu
    volumes:
      - nominatim-data:/var/lib/postgresql/12/main
    shm_size: 1gb

volumes:
  nominatim-data:
```

**Expected behavior**
There must be an fuzzy search
