### ISSUE TITLE
After Rank 30 Import an error happened, all data gone

### ISSUE THREAD

**Issue by ChaosEmpire** [mediagis/nominatim-docker#354]
Nominatim 4.01 pulled at 2.8.22

imported first time data, after ~24h rank 30 was finished
the folliwing log was available, incl crash.
after that..all data gone, impoirt starts again :(

2022-08-02 23:10:39: Post-process tables

Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 11, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 235, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 96, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 119, in run
    database_import.create_search_indices(conn, args.config,
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/database_import.py", line 236, in create_search_indices
    sql.run_sql_file(conn, 'indices.sql', drop=drop)
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/sql_preprocessor.py", line 88, in run_sql_file
    cur.execute(sql)
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/connection.py", line 27, in execute
    super().execute(query, args)
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 142, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

+ trap stopServices TERM
+ /app/config.sh
+ id nominatim
user nominatim already exists
+ echo 'user nominatim already exists'
+ IMPORT_FINISHED=/var/lib/postgresql/12/main/import-finished
+ TOKENIZER_DIR=/nominatim/tokenizer
+ '[' '!' -f /var/lib/postgresql/12/main/import-finished ']'
+ /app/init.sh
+ OSMFILE=/nominatim/data.osm.pbf
Skipping optional Wikipedia importance import
+ '[' false = true ']'
+ '[' -f false ']'
+ echo 'Skipping optional Wikipedia importance import'
+ '[' '' = true ']'
+ '[' -f '' ']'
+ echo 'Skipping optional GB postcode import'
+ '[' '' = true ']'
+ '[' -f '' ']'
+ echo 'Skipping optional US postcode import'
Skipping optional GB postcode import
Skipping optional US postcode import
+ '[' '' = true ']'
+ '[' -f '' ']'
+ echo 'Skipping optional Tiger addresses import'
+ '[' '' '!=' '' ']'
+ '[' /nominatim/data/merged.osm.pbf '!=' '' ']'
+ echo Reading OSM extract from /nominatim/data/merged.osm.pbf
+ OSMFILE=/nominatim/data/merged.osm.pbf
+ '[' '!' -f /var/lib/postgresql/12/main/PG_VERSION ']'
+ sudo service postgresql start
Skipping optional Tiger addresses import
Reading OSM extract from /nominatim/data/merged.osm.pbf
 * Starting PostgreSQL 12 database server
   ...done.
+ sudo -E -u postgres psql postgres -tAc 'SELECT 1 FROM pg_roles WHERE rolname='\''nominatim'\'''
+ grep -q 1
+ sudo -E -u postgres psql postgres -tAc 'SELECT 1 FROM pg_roles WHERE rolname='\''www-data'\'''
+ grep -q 1
+ sudo -E -u postgres psql postgres -tAc 'ALTER USER nominatim WITH ENCRYPTED PASSWORD '\''Passwort'\'''
ALTER ROLE
+ sudo -E -u postgres psql postgres -tAc 'ALTER USER "www-data" WITH ENCRYPTED PASSWORD '\''Passwort'\'''
ALTER ROLE
+ sudo -E -u postgres psql postgres -c 'DROP DATABASE IF EXISTS nominatim'
DROP DATABASE
+ chown -R nominatim:nominatim /nominatim
+ cd /nominatim
+ sudo -E -u nominatim nominatim import --osm-file /nominatim/data/merged.osm.pbf --threads 4
2022-08-02 23:24:15: Using project directory: /nominatim
2022-08-02 23:24:16: Creating database
2022-08-02 23:24:17: Setting up country tables
2022-08-02 23:24:19: Importing OSM data file
2022-08-02 23:24:19  osm2pgsql version 1.5.1
2022-08-02 23:24:19  Database version: 12.11 (Ubuntu 12.11-0ubuntu0.20.04.1)
2022-08-02 23:24:19  PostGIS version: 3.0
2022-08-02 23:24:19  Parsing gazetteer style file '/usr/local/etc/nominatim/import-full.style'.
NOTICE:  table "place" does not exist, skipping

**Comment by Mastercuber** [comment]
I have the same problem with Version 4.1. Starting the server with the following `docker-compose` file works just fine:
```yaml
version: "3"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.0
        restart: always
        ports:
            - "9032:8080"
        environment:
            PBF_URL: https://download.geofabrik.de/europe/germany/baden-wuerttemberg-latest.osm.pbf
            REPLICATION_URL: https://download.geofabrik.de/europe/germany/baden-wuerttemberg-updates/
            IMPORT_WIKIPEDIA: 'false'
            IMPORT_GB_POSTCODES: 'false'
            IMPORT_US_POSTCODES: 'false'
            THREADS: 8
            NOMINATIM_PASSWORD: strong-pw
            POSTGRES_EFFECTIVE_CACHE_SIZE: 18GB
            IMPORT_STYLE: address
        volumes:
            - nominatim-data:/var/lib/postgresql/12/main
        shm_size: 1gb

volumes:
    nominatim-data:
```
Switching to Version 4.1 like in the next compose file, gives me the following error before the container is restarted and the import process starts over again:
![Bildschirmfoto vom 2022-10-14 15-49-17](https://user-images.githubusercontent.com/14162739/195880919-25b540a5-a7b6-4608-a5cf-d42d0a222e39.png)

Here the compose file for 4.1:
```yaml
version: "3"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.1
        restart: always
        ports:
            - "9032:8080"
        environment:
            PBF_URL: https://download.geofabrik.de/europe/germany/baden-wuerttemberg-latest.osm.pbf
            REPLICATION_URL: https://download.geofabrik.de/europe/germany/baden-wuerttemberg-updates/
            IMPORT_WIKIPEDIA: 'false'
            IMPORT_GB_POSTCODES: 'false'
            IMPORT_US_POSTCODES: 'false'
            THREADS: 8
            NOMINATIM_PASSWORD: strong-pw
            POSTGRES_EFFECTIVE_CACHE_SIZE: 18GB
            IMPORT_STYLE: address
        volumes:
            - nominatim-data:/var/lib/postgresql/14/main
        shm_size: 1gb

volumes:
    nominatim-data:
```
