### ISSUE TITLE
Import fails with index check error (v.4.1) 

### ISSUE THREAD

**Issue by IvanShift** [mediagis/nominatim-docker#365]
**Describe the bug**
Import always ends with an index check error (tried on different PCs and servers):
With v.4.0 everything is OK.
```
+ '[' -f tiger-nominatim-preprocessed.csv.tar.gz ']'
+ sudo -E -u nominatim nominatim admin --check-database
2022-08-26 20:09:08: Using project directory: /nominatim
2022-08-26 20:09:08: Checking database
Checking database connection ... OK
Checking for placex table ... OK
Checking for placex content ... OK
Checking that tokenizer works ... OK
Checking for wikipedia/wikidata data ... WARNING

Wikipedia/Wikidata importance tables missing.
Quality of search results may be degraded. Reverse geocoding is unaffected.
See https://nominatim.org/release-docs/latest/admin/Import/#wikipediawikidata-rankings

Checking indexing status ... Failed
The indexing didn't finish. 61006 entries are not yet indexed.

To index the remaining entries, run:   nominatim index

Checking that database indexes are complete ... OK
Checking that all database indexes are valid ... OK
Checking TIGER external data table. ... not applicable

```

**To Reproduce**
I use this docker-compose file:
```
version: "3.6"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.1
        restart: always
        ports:
            - "6080:8080"
        environment:
            PBF_URL: https://download.geofabrik.de/russia-latest.osm.pbf
            REPLICATION_URL: https://download.geofabrik.de/russia-updates/
            NOMINATIM_PASSWORD: very_password_123
            UID: 2082
        volumes:
            - nominatim-pg:/var/lib/postgresql/14/main
        shm_size: 8gb

volumes:
    nominatim-pg:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /media/dev/osm
```

**Expected behavior**
Successful import

**Screenshots & Logs**
[full_log.log](https://github.com/mediagis/nominatim-docker/files/9436206/full_log.log)

**Desktop / Server (please complete the following information):**
 - OS & Version: Ubuntu 22.04
 - Docker Version: 20.10.12
 - Nominatim Version: 4.1
