### ISSUE TITLE
container stops logging after update/replication run

### ISSUE THREAD

**Issue by Schmoho** [mediagis/nominatim-docker#403]
**Describe the bug**
After the run of a continuous replication update the container does not resume logging  on the Apache process

**To Reproduce**
1. 
```yml
  nominatim:
    image: mediagis/nominatim:4.1
    volumes:
      - nominatimdata:/var/lib/postgresql/14/main
      - nominatimlogs/:/var/log/postgresql/
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    environment:
      PBF_URL: https://download.geofabrik.de/europe/germany-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/europe/germany-updates/
      UPDATE_MODE: "continuous"
      NOMINATIM_REPLICATION_UPDATE_INTERVAL: 86400
      IMPORT_WIKIPEDIA: false
```
2. Wait for update
3. `docker logs <nominatim-container>`

**Expected behavior**
Container resumes normal logging.

**Desktop / Server (please complete the following information):**
 - OS & Version: Ubuntu 22.04.1
 - Docker Version: 20.10.20
 - Nominatim Version: 4.1 Container
