### ISSUE TITLE
403 to get tiger data

### ISSUE THREAD

**Issue by acpguedes** [mediagis/nominatim-docker#459]
**Describe the bug**
I'm getting 403 error to download the tiger data, and this are leading my docker to fail

https://github.com/mediagis/nominatim-docker/issues/455#issuecomment-1598910896

**To Reproduce**
1. contrib/docker-compose.ylm
2. 
```
version: "3"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.2
        restart: always
        ports:
            - "8080:8080"
        environment:
            # see https://github.com/mediagis/nominatim-docker/tree/master/4.2#configuration for more options
            PBF_URL: https://download.geofabrik.de/south-america/brazil-latest.osm.pbf
            REPLICATION_URL: https://download.geofabrik.de/south-america/brazil-updates/
            NOMINATIM_PASSWORD: very_secure_password
            IMPORT_TIGER_ADDRESSES: 'true'
        volumes:
            - nominatim-data:/var/lib/postgresql/14/main
        shm_size: 1gb

volumes:
    nominatim-data:
```

4. `docker-compose -f contrib/docker-compose.yml up`

**Expected behavior**
I like to built a local instance of nominatim to use API to reverser searches.
I need to get a ZipCode given a lat-log or addess (on Brazil)

**Screenshots & Logs**

Fail in this step
![image](https://github.com/mediagis/nominatim-docker/assets/1912449/fca62efd-f24b-441e-b8cb-a07cf36528a3)
The connection within container are working
![image](https://github.com/mediagis/nominatim-docker/assets/1912449/b2a618b4-b5a2-41fc-84c0-3071b4db9fdf)
Outside container I still getting a 403
`$ curl -L -A mediagis/nominatim-docker:4.2.3 --fail-with-body https://nominatim.org/data/tiger2021-nominatim-preprocessed.csv.tar.gz -o nominatim/tiger-nominatim-preprocessed.csv.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0    187      0 --:--:-- --:--:-- --:--:--   187
curl: (22) The requested URL returned error: 403`

**Desktop / Server (please complete the following information):**
 - OS & Version: Ùbuntu server 22
 - Docker Version: docker-compose version 1.29.2 & Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3
 - Nominatim Version: 4.2.3
