### ISSUE TITLE
Mounting flatnode as volume causes process stall at NOTICE:  table "place" does not exist, skipping

### ISSUE THREAD

**Issue by alekw** [mediagis/nominatim-docker#468]
**Describe the bug**
I tried to set up instance with docker-compose as below, and noticed that process stalls on this line for hours: 
`nominatim    | NOTICE:  table "place" does not exist, skipping`

```
version: "2.3"
services:
  nominatim:
    image: mediagis/nominatim:4.2
    container_name: nominatim
    restart: always
    ports: 
      - 8080:8080
    environment: 
      - PBF_URL=https://download.geofabrik.de/europe/andorra-latest.osm.pbf
      - REPLICATION_URL=https://download.geofabrik.de/europe/andorra-updates
      - REPLICATION_RECHECK_INTERVAL=86400
      - NOMINATIM_PASSWORD=12345678
      - THREADS=48
    volumes:
      - ./db:/var/lib/postgresql/14/main
      - ./flatnode:/nominatim/flatnode
    shm_size: 16gb
```
The line that causes the issue is mounting flatnode.

**To Reproduce**
1. Save my docker-compose.yml
2. Command: docker-compose up
3. See output
4. Repeat  when ./flatnode mount is not present

**Expected behavior**
I expected setup to finish in similar time. In my case 2 minutes without flatnode, and at least 2 hours with it (I cancelled then)

**Screenshots & Logs**
If applicable, add screenshots & logs to help explain your problem.

```
nominatim    | + cd /nominatim
nominatim    | + '[' '' = true ']'
nominatim    | + sudo -E -u nominatim nominatim import --osm-file /nominatim/data/andorra-latest.osm.pbf --threads 48
nominatim    | 2023-08-08 21:53:32: Using project directory: /nominatim
nominatim    | 2023-08-08 21:53:35: Creating database
nominatim    | 2023-08-08 21:53:36: Setting up country tables
nominatim    | 2023-08-08 21:53:38: Importing OSM data file
nominatim    | 2023-08-08 21:53:38  osm2pgsql version 1.7.2
nominatim    | 2023-08-08 21:53:38  Database version: 14.8 (Ubuntu 14.8-0ubuntu0.22.04.1)
nominatim    | 2023-08-08 21:53:38  PostGIS version: 3.2
nominatim    | 2023-08-08 21:53:38  Parsing gazetteer style file '/usr/local/etc/nominatim/import-full.style'.
nominatim    | NOTICE:  table "place" does not exist, skipping
```

**Desktop / Server (please complete the following information):**
 - OS & Version: SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux

 - Docker Version: 20.10.14
 - Nominatim Version: 4.2.0
