### ISSUE TITLE
During setup, indexing, `INSERT INTO`, hit `errors.InsufficientPrivilege`.  

### ISSUE THREAD

**Issue by mjbroerman** [mediagis/nominatim-docker#488]
**Describe the bug**
During setup, indexing, `INSERT INTO`, hit `errors.InsufficientPrivilege`.  

**To Reproduce**
1. Run this command

```
docker compose -f docker-compose.yml up
```
With this `docker-compose.yml`
```
version: "3"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.2
        restart: always
        ports:
            - "8080:8080"
        environment:
            # see https://github.com/mediagis/nominatim-docker/tree/master/4.2#configuration for more options
            PBF_URL: https://download.geofabrik.de/north-america/us/pennsylvania-latest.osm.pbf
            REPLICATION_URL: https://download.geofabrik.de/north-america/us/pennsylvania-updates
            NOMINATIM_PASSWORD: qaIACxO6wMR3
        volumes:
            - nominatim-data:/var/lib/postgresql/14/main
        shm_size: 1gb

volumes:
    nominatim-data:
```

2. See error

```
nominatim  | Traceback (most recent call last):
nominatim  |   File "/usr/local/bin/nominatim", line 14, in <module>
nominatim  |     exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
nominatim  |   File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 264, in nominatim
nominatim  |     return parser.run(**kwargs)
nominatim  |   File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 126, in run
nominatim  |     return args.command.run(args)
nominatim  |   File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 134, in run
nominatim  |     indexer.index_full(analyse=not args.index_noanalyse)
nominatim  |   File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 140, in index_full
nominatim  |     if self.index_by_rank(26, 30) > 1000:
nominatim  |   File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 174, in index_by_rank
nominatim  |     total += self._index(runners.RankRunner(rank, analyzer), 20 if rank == 30 else 1)
nominatim  |   File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 234, in _index
nominatim  |     runner.index_places(pool.next_free_worker(), part)
nominatim  |   File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 201, in next_free_worker
nominatim  |     return next(self.free_workers)
nominatim  |   File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 209, in _yield_free_worker
nominatim  |     if thread.is_done():
nominatim  |   File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 159, in is_done
nominatim  |     if self.conn.poll() == psycopg2.extensions.POLL_OK:
nominatim  | psycopg2.errors.InsufficientPrivilege: could not open file "base/49152/81922_fsm": Read-only file system
nominatim  | CONTEXT:  SQL statement "INSERT INTO location_road_2 (partition, place_id, country_code, geometry)
nominatim  |       values (in_partition, in_place_id, in_country_code, in_geometry)"
nominatim  | PL/pgSQL function insertlocationroad(integer,bigint,character varying,geometry) line 22 at SQL statement
nominatim  | PL/pgSQL function placex_update() line 464 at assignment
```

**Expected behavior**
Expected container setup finish and exposed api

**Screenshots & Logs**
This was the out just prior. As far as I can tell, no issue prior to this
```
nominatim  | 2023-10-11 17:22:46: Done 122839 in 231 @ 531.129 per second - rank 26 ETA (seconds): 672.72
nominatim  | 2023-10-11 17:22:46: Done 123370 in 232 @ 531.642 per second - rank 26 ETA (seconds): 671.07
nominatim  | 2023-10-11 17:22:47: Done 123901 in 232 @ 531.868 per second - rank 26 ETA (seconds): 669.79
nominatim  | 2023-10-11 17:22:48: Done 124432 in 233 @ 531.960 per second - rank 26 ETA (seconds): 668.67
nominatim  | 2023-10-11 17:22:49: Done 124963 in 234 @ 532.157 per second - rank 26 ETA (seconds): 667.43
nominatim  | 2023-10-11 17:22:50: Done 125495 in 235 @ 532.636 per second - rank 26 ETA (seconds): 665.83
nominatim  | 2023-10-11 17:22:51: Done 126027 in 236 @ 533.338 per second - rank 26 ETA (seconds): 663.96
nominatim  | 2023-10-11 17:22:51: Done 126560 in 237 @ 533.900 per second - rank 26 ETA (seconds): 662.26
```

**Desktop / Server (please complete the following information):**
 - OS & Version: macOS Ventura 
 - Docker Version: 4.22.0
 - Nominatim Version: 4.2
