### ISSUE TITLE
Planet-Import is slow on very potent server

### ISSUE THREAD

**Issue by georgbachmann** [mediagis/nominatim-docker#511]
I am using the latest docker image using this docker-compose configuration:
```
version: "3.4"

services:

  nominatim:
    image: mediagis/nominatim:4.3
    shm_size: '4gb'
    environment:
      - PBF_PATH=/osm/planet-latest.osm.pbf
      - NOMINATIM_PASSWORD=test
      - POSTGRES_SHARED_BUFFERS='4GB'
      - THREADS=50
      - NOMINATIM_ADDRESS_LEVEL_CONFIG=/config/our_own_ranks.json
    volumes:
      - ./nominatim-data:/var/lib/postgresql/12/main
      - ./flatnode:/nominatim/flatnode
      - ./osm:/osm
      - ./config:/config
```

When I try to import a smaller extract on my local machine (a MacBook M1) it suuuuuper fast. So I do understand the stages of the import. And the osm2psql part ist fast on my local machine as well as the rankings afterwards. I get like 2000+ items per second. That seems fine?!?

So now on my server, which is a machine with 60 CPU cores, about 300!!GB of RAM and fast NVME drives, the osm2psql part is also super fast, but when it then starts to rank things, it turns super slow...

```
2023-12-13 07:12:55: Done 3107220 in 12238 @ 253.895 per second - rank 30 ETA (seconds): 1260190.67
```

So like 250-ish items per second, which would result in an import time of around 2 weeks.
I am not really good at optimizing postgres, but I guess I that will be my problem?

Would be suuuuuper happy about help on what in my postgres config is wrong and therefore slowing everything down.

**Desktop / Server (please complete the following information):**
 - OS & Version: Ubuntu 22.04.3 LTS
 - Docker Version: 20.10.21
 - Nominatim Version: 4.3
