### ISSUE TITLE
remote postgres host parse error

### ISSUE THREAD

**Issue by ErrorCode996** [mediagis/nominatim-docker#534]
**unable to connect to remote digital ocean db**

**deployment.yml**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nominatim-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nominatim
  template:
    metadata:
      labels:
        app: nominatim
    spec:
      containers:
        - name: nominatim
          image: mediagis/nominatim:4.3
          env:
            - name: PBF_URL
              value: "https://download.geofabrik.de/europe/united-kingdom-latest.osm.pbf"

            - name: REPLICATION_URL
              value: "https://download.geofabrik.de/europe/united-kingdom-updates"

            - name: NOMINATIM_DATABASE_DSN
              value: pgsql:dbname=test;port=XXXX;hostaddr=XXXXX.c.db.ondigitalocean.com;user=XXXX;password=XXXXX

            - name: NOMINATIM_TOKENIZER
              value: icu

            - name: PGHOSTADDR
              value: XXXXXXXXX.c.db.ondigitalocean.com

            - name: PGDATABASE
              value: test

            - name: PGUSER
              value: XXXX

            - name: PGPASSWORD
              value: XXXX

            - name: PGPORT
              value: XXXX
```

**LOG**
```
+ chown -R nominatim:nominatim /nominatim
+ cd /nominatim
+ '[' '' = true ']'
+ sudo -E -u nominatim nominatim import --osm-file /nominatim/data.osm.pbf --threads 8
Using project directory: /nominatim
Creating database
createdb: error: could not parse network address "xxxxxxx.c.db.ondigitalocean.com": Name or service not known
FATAL: Creating new database failed.
```
