### ISSUE TITLE
psycopg2.OperationalError: server closed the connection unexpectedly

### ISSUE THREAD

**Issue by rmallol** [mediagis/nominatim-docker#565]
**Describe the bug**
Automatic import from docker image returns error after running for a while.

**To Reproduce**
1. Use command 'docker run -it \
  -e PBF_URL=https://download.geofabrik.de/europe/spain/cataluna-latest.osm.pbf \
  -e POSTGRES_CHECKPOINT_TIMEOUT=20min \
  -p 8080:8080 \
  --name nominatim \
  mediagis/nominatim:4.4'
2. See error
psycopg2.OperationalError: server closed the connection unexpectedly
                 This probably means the server terminated abnormally
                 before or while processing the request.

**Expected behavior**
Nominatim is installed correctly.

**Screenshots & Logs**
![nominatim issue](https://github.com/mediagis/nominatim-docker/assets/73774413/9fde0097-3667-492a-8433-6971cd8d7129)

**Desktop / Server (please complete the following information):**
 - OS & Version: [macOS Big Sur 11.7.8]
 - Docker Version: [3.6.0]
 - Nominatim Version: [4.4]

**Additional context**
 - RAM: 8 GB 1600 MHz DDR3

**Comment by mtmail** [comment]
Thanks for the hardware info.

The postgresql logfiles inside the container might have a better error message. But effectively Postgresql crashes and usually that's because it hit a hardware limit. On a local machine we can rule out network (network mounted storage).

The https://github.com/mediagis/nominatim-docker/tree/master/4.4#postgresql-tuning default are probably too large for an 8GB machine, they were chosen for a 64GB machine. And on a desktop computer the 8GB might not even be available. Try configuring lower values. (https://postgresqlco.nf/doc/en/param/shared_buffers/14/)

**Comment by shadowbeat070** [comment]
I've experienced this bug as well, tbh i'm still not quite sure of the cause. 

I can reproduce this bug by running the following docker compose 
``` 
services:
  nominatim:
    image: mediagis/nominatim:4.4
    environment:
      - PBF_URL=https://download.geofabrik.de/europe/netherlands-latest.osm.pbf
      - REPLICATION_URL=https://download.geofabrik.de/europe/netherlands-updates/
    ports:
      - "8080:8080"
    container_name: nominatim
    ```
    
however if ran the following command : "docker run -it -e PBF_URL=https://download.geofabrik.de/europe/netherlands-latest.osm.pbf -e REPLICATION_URL=https://download.geofabrik.de/europe/netherlands-updates/ -p 8080:8080 --name nominatim mediagis/nominatim:4.4" 
it would succeed. Im running both commands/services on the exact same machine.
what i assume to be the reason is that whenever use the docker compose file it uses my C drive which is but when runnnig through the docker command it will use my E drive which is larger, faster and has more space than my C drive.

I'm not too sure about the details of the problem but this was what fixed it for me.
